export const QUERY_KEYS = {
  BOOKS: "books",
  BOOK_DETAIL: "bookDetail",
  BOOKS_RECOMMEND: "booksRecommend",
  AUTHORS: "authors",
  AUTHORS_POPULAR: "authorsPopular",
  AUTHOR_BOOKS: "authorBooks",
  CATEGORIES: "categories",
  CART: "cart",
  CART_CHECKOUT: "cartCheckout",
  LOANS_MY: "loansmy",
  ME: "me",
  ME_LOANS: "meLoans",
  ME_REVIEWS: "meReviews",
  REVIEWS_BOOK: "reviewsBook",
  ADMIN_OVERVIEW: "adminOverview",
  ADMIN_BOOKS: "adminBooks",
  ADMIN_LOANS: "adminLoans",
  ADMIN_LOANS_OVERDUE: "adminLoansOverdue",
  ADMIN_USERS: "adminUsers",
}
